README.md

This updates the README with a rough draft of contributing instructions #7. I wanted to explain the use of labels for the Waffle.io integration as well as provide an option for branch naming.
I'm not really married to naming convention I provided, so let me know if you want to go a different direction.

Add first draft of contribution instructions

---

package-lock.json
package.json
src/App.js
src/Header.js

This PR closes #27 
- Add @material-ui/icons as a dependency to use built-in icons.
- Creates a new `Header` component using Material UI components

Implement initial header containing menu button and logo.

---

src/App.jsx
src/App.test.js

This PR is not associated with an issue.
Adds an initial test for the `<App/>` component using [Enzyme's shallow rendering](https://airbnb.io/enzyme/docs/api/shallow.html) to find a certain number of components.

Update App test to test for finding elements

---

README.md

This PR does not address an issue.
Removes the Waffle badge from the README.

remove Waffle badge from README

---

src/utils/searchParams.test.js
src/utils/searchParams.ts

This PR does not address an issue.
Adds a `getSearchParam` utility that can be used to grab the value of a URL search parameter. If the parameter does not exist or has no value, the utility will return `null`.
This utility will eventually be used in a future PR to grab a resource's ID from the URL.

Add getSearchParam utility

---

src/App.styles.ts
src/components/Header.tsx
src/components/Home.tsx
src/components/HomeButton.tsx
src/components/HomeButtons.tsx
src/components/Search.tsx

This PR doesn't close an issue.
- restructures the `font` object in App.styles
- implements a `convertPixelsToRems()` helper in the `font` object that will do as it's named
- updates and usage of pixels in styles to use rems (via `convertPixelsToRems`)
I'm not sure if the helper itself should live inside the font object, but let me know what you think.

Add convertPixelsToRems() helper

---

src/components/Resource.test.tsx
src/components/Resource.tsx

- updates the loading spinner to be rendered when no resource is present
- updates the corresponding test

Fix loading spinner on individual service page

---

src/components/ResourceCard.tsx

This removes the plus button from the resource cards on the category pages.

remove plus button from Resource Card

---

src/components/BackButton.tsx
src/components/CategoryBanner.tsx
src/components/CategoryResults.tsx
src/components/Details.tsx
src/components/PageBanner.tsx
src/components/Resource.tsx
src/components/__tests__/Resource.test.tsx

- creates a `<BackButton/>` component
- adds a back button to an individual resource page
- replaces current back button found on category page with new component
- adds a page banner similar to the one found on the category page

add back button and banner to resource

---

src/components/SubCategories.tsx

- updates the sub-category selector to overflow-x via scroll
- updates the horizontal padding on the sub-category container to be equal while maintaining perceived spacing via margin
I think some design work may be needed in the future for ensuring it's obvious there is more content to the right, but this is a step in the right direction.

fix overflow issue with SubCategories

---

src/components/HomeLink.tsx

Ensures that home buttons stretch to fill the height of their current row.

fix home page buttons not stretching

---

src/utils/getPreFilledLink/getScheduleUrlParams/index.ts

Adds handling for missing schedules on the resource page. This will prevent the page from crashing on those resources.

add handling for a missing schedule on resource page

---

package-lock.json
package.json
src/App.tsx
src/components/About.tsx
src/components/Header.tsx
src/components/Icons.tsx
src/components/MenuDrawer.tsx
src/components/PrivacyPolicy.tsx
src/components/TermsOfService.tsx
src/components/TermsOfUse.tsx

This PR closes #126 .
- adds a main menu that opens on the hamburger button found in the header
- adds "About", "Terms of Use", and "Privacy Policy" pages
- updates `@material-ui/icons` to the latest version

Add main menu #126

---

src/App.styles.ts
src/components/Header.tsx

- adds a bit of horizontal padding on the main `<Container/>` ensure content doesn't hug edge of screen
- removes extra, horizontal padding in the header added by MUI's `<Toolbar/>`
- reduces the top margin of the header

Style Fixes

---

src/components/Map.tsx

Adds a simple `console.log()` in `<Map/>`.

logging of an error in <Map/>

---

packages/upswyng-server/src/data-pipeline/updateAlgolia.ts
packages/upswyng-server/src/models/Resource.ts
packages/upswyng-server/src/routes/api/resource/[id].ts
packages/upswyng-server/src/routes/api/resource/draft/[id].ts
packages/upswyng-server/src/routes/api/resource/draft/approve/[id].ts
packages/upswyng-server/src/routes/api/resource/draft/delete/[id].ts
packages/upswyng-server/src/routes/api/resource/index.ts
packages/upswyng-server/src/routes/api/subcategory/add-resource.ts
packages/upswyng-server/src/routes/resource/[id].svelte
packages/upswyng-server/src/routes/resource/draft/[id].svelte

After refactoring the types between `TResourceDocument` and `TResource`, a bunch of stuff broke. Fix it.
- Fix drafts of resources not being saved due to `ObjectId` problems
- Fix drafts of resources not being approved due to a bug in `resourceToSchema` where either `id` or `_id` may have not been populated
- Fix types on interface of `Resource` model which had already been updated on `DraftResource` model
- Fixes `TResourceDocument` not being converted to `TResource` before being sent over the wire, which was causing the map not to show on the web client

🚑 Fix all kinds of resource errors

---

packages/upswyng-server/jest.config.js

I was getting an error when VSCode started: 'Starting Jest in Watch mode failed too many times and has been stopped'. This issue (https://github.com/facebook/jest/issues/3254) suggests ignoring node_modules, so I will try that.

🐛 Ignore node_modules in server jest config

---

package.json

They had been turned off during CI troubleshooting.

✅ Reeanable server tests

---

packages/upswyng-server/src/routes/resource/issues/index.svelte

When fetched count was below 1, page failed because pagination step would be set to 0 which caused the skip value to be negative.

🐛 Don't allow issues pagination step below 1

---

.vscode/settings.json
packages/upswyng-server/src/components/ResourceScheduleDisplay.svelte
packages/upswyng-server/src/models/Resource.ts
packages/upswyng-server/src/models/Subcategory.ts
packages/upswyng-server/src/models/Utility.ts

Diffs being stored with Draft Approval Event Logs weren't being stored properly, and diffs with schedules weren't being shown correctly.

🐛 Fix errors with Event Log diffs

---

packages/upswyng-types/package.json
packages/upswyng-types/rollup.config.js
yarn.lock

Previously build was done just using typescript, but not producing a
commonjs module and an esm module was causing problems down the road.
The rollup config is branched from that of upswyng-core and is basically
the same, just pared down a bit.

🏗 Build upwsyng-types with rollup

---

packages/upswyng-web/package.json
packages/upswyng-web/src/components/Schedule.tsx

Fixes the rendering of weekly schedules in the public section of the app.
_Note: This does not include monthly or annual schedules._

fix rendering of Weekly schedules

---

packages/upswyng-server/src/components/ScheduleSelector.svelte

The selector to pick certain weeks of the month had some wonky behavior. Now, "All" starts off as selected and then once any single week is selected "All" becomes unselected. If "All" is pressed later all the individual weeks will be unselected.

💄 [server] Tweak the behavior of sked weekly repeat selector

---

packages/upswyng-server/src/routes/api/resource/issues/[resourceId].ts
packages/upswyng-server/src/routes/resource/[resourceId].svelte

[This all applies to admins only] Previous behavior was only to show unresolved issues on the the resource page. (Also there was a bug where the "Issues" header would show even with no issues.) The new behavior is:
- show banner when unresolved issues exist
- show all issues at the bottom, even the resolved ones
- hide the header if there are no issues

💄 [server] Always show issues for resource

---

packages/upswyng-server/src/components/EventLogs.svelte
packages/upswyng-server/src/components/Nav.svelte
packages/upswyng-server/src/routes/api/eventlogs.ts
packages/upswyng-server/src/routes/eventlogs.svelte
packages/upswyng-server/src/routes/resource/[resourceId].svelte
packages/upswyng-server/src/routes/resource/draft/[_id].svelte
packages/upswyng-server/src/routes/resource/index.svelte
packages/upswyng-server/src/routes/resource/issue/[resource_issue_id].svelte
packages/upswyng-server/src/routes/resource/issues/index.svelte

- Show a subset of event logs relating to a resource on the resource page
- Add a tag/badge next to everything that only admins can see so that it's clear the feature is admin-only

✨ [server] Show related event logs on resource page

---

packages/upswyng-server/src/app.ts

Modify the session config in an attempt to fix the intermittent grant config error in issue #230. Some settings were set counter to some of the recommendations in [the docs](https://www.npmjs.com/package/express-session#options). I can't replicate this right now in the dev server so I'm just trying something out.

🐛 [server] Attempt to fix authentication bug

---

packages/upswyng-server/src/routes/logout.ts
packages/upswyng-server/src/service-worker.js
packages/upswyng-server/src/utility/userMiddleware.ts

Disable Sapper service-worker caching for auth routes. Add some logging for when grant `id_token` is not defined. #230

🐛 [server] Disable service worker caching for auth routes

---

packages/upswyng-server/src/app.ts

Still desperately trying to fix #230. I'm not even sure if this is necessary, but I want to try to fix the order of the `session` and `grant` middlewares and not have them in a race condition.

🐛 [server] Separate middleware layers

---

packages/upswyng-server/src/app.ts

Still troubleshooting the missing session problem. The database shows no sessions created at all. I'm thinking the Mongoose Connection may not yet be made when it's passed to the session middleware.

[server] Temporarily store sessions in memory

---

packages/upswyng-web/src/App.tsx
packages/upswyng-web/src/components/CoordinatedEntry.tsx
packages/upswyng-web/src/components/HomeButtons.tsx
packages/upswyng-web/src/components/PageBanner.tsx
packages/upswyng-web/src/theme/index.ts

- adds a "Coordinated Entry" landing page the user visits with important information
- updates the MUI theme shape to not have a border radius (keep'n things square)

feat: add coordinated entry page

---

.travis.yml
packages/upswyng-server/.env.example
packages/upswyng-server/Procfile
packages/upswyng-server/package.json
packages/upswyng-server/src/worker.ts
packages/upswyng-server/worker.rollup.config.js
packages/upswyng-types/src/index.ts
packages/upswyng-types/src/worker.ts
yarn.lock

Create a second process (in addition to the server) which will run on Heroku in order to execute long-running or scheduled jobs.
Some ideas for those:
- scanning the resources for bad URLs
- syncing resources to algolia search
- mirroring the database to a staging tier
- sync with strappd
The worker process pulls jobs from a [BullMQ](https://github.com/taskforcesh/bullmq) queue with a Redis cache as the backing store.

✨ [server] Create worker job

---

packages/upswyng-web/src/components/MonthlySchedule.tsx
packages/upswyng-web/src/components/Resource.tsx
packages/upswyng-web/src/components/Schedule.tsx
packages/upswyng-web/src/components/WeeklySchedule.tsx
packages/upswyng-web/src/theme/index.ts

Adds a custom display for monthly schedules.
_individual monthly schedule display example_
_example with a weekly and monthly schedule combination_

feat: add monthly schedule display

---

packages/upswyng-core/src/ResourceSchedule.ts

- updates the date compared against RRule instances to be UTC, as RRule expects
This fixes the displaying of "next open at" in the web app and fixes the tests associated with this logic in core.

fix: update date comparison to use UTC

---

packages/upswyng-web/src/App.tsx
packages/upswyng-web/src/components/NotFound.tsx

This PR closes #290
Adds a "not found" component that renders whenever a faulty URL is entered.

🧼 add "not found" component

---

packages/upswyng-server/src/components/Job.svelte

- Add `kind` to top-level display so user doesn't have to open details to see what kind of job they're looking at
- Make the job ID monospace for consistency with the rest of the UI
- Add button to copy the job ID to the clipboard

✨ [server] Add job kind and ID copy button to Job display

---

packages/upswyng-core/src/index.ts
packages/upswyng-web/src/components/MenuDrawer.tsx
packages/upswyng-web/src/components/ResourceCard.tsx
packages/upswyng-web/src/components/ResourceList.tsx
packages/upswyng-web/src/components/WeeklySchedule.tsx
packages/upswyng-web/src/theme/index.ts

- updates the resource list for categories and sub-categories to use [MUI's card component](https://material-ui.com/components/cards/#card)
- darkens the paper background, used on MUI cards, in the MUI theme
- overrides the paper background color in the main menu drawer to use the default app background
We noticed that the text laying on top of the image was occasionally difficult to read, so we're moving it off the image and implementing an updated layout

update resource list layout

---

packages/upswyng-server/src/data-pipeline/setupCategories.ts
packages/upswyng-web/src/components/Categories.tsx

This PR does not close an issue
- removes "Lite Rail" sub-category from displaying in public-facing app, since our initial launch will target Boulder County
- removes "Day Labor" sub-category from displaying in public-facing app, since it is redundant with "Ready to Work" in Boulder County
- updates the displayed name for the "Bus" category to "Bus Passes"

feat: edit displayed sub-categories in public app

---

packages/upswyng-web/src/components/ResourceCard.tsx
packages/upswyng-web/src/components/ResourceList.tsx
packages/upswyng-web/src/theme/index.ts
packages/upswyng-web/src/utils/schedule.ts

- adds more prominent open/closed labels to resource list
- moves individual resource parsing from resource list to card
- adds success color to theme palette
- removes unnecessary `CardColor` interface in `<ResourceCard/>`

add more prominent open/closed labels

---

packages/upswyng-server/src/routes/api/alert/[alert_id].ts

Endpoint was checking to make sure the provided alert ID was a valid `ObjectId` but then not using the result.

🐛 [server] Fix unused var in alert endpoint

---

packages/upswyng-web/src/components/HotlineCard.tsx

This PR closes #330
1. Updates the way phone numbers are called so that it works on all browsers 😅 
2. Makes the phone number link intuitive 
3. Locks the "more / less" button in place so it is not floating up and down and running away from your mouse

updt: improve hotline page

---

.eslintignore
.gitignore
package.json
packages/web/cypress.json
packages/web/cypress/fixtures/api/weather.json
packages/web/cypress/integration/web.ts
packages/web/cypress/plugins/index.ts
packages/web/cypress/support/commands.ts
packages/web/cypress/support/index.ts
packages/web/cypress/tsconfig.json
packages/web/package.json
packages/web/src/components/useSearchResults.tsx
tsconfig.base.json

- Set up cypress integration tests. These tests will have the API server mocked. (see https://docs.cypress.io/api/commands/fixture.html#Syntax)
- Modify `useSearchResults` hook -- when credentials for algolia aren't provided AND the environment is not `production` it logs a message and goes into no-op mode. This will allow Travis to run integration tests without algolia keys
- Add a mock data fixture for the weather endpoint
- Stub a blank response for the alert search endpoint

✅ [web] Add integration test framework

---

packages/server/src/app.ts
packages/server/src/components/FacebookLoginButton.svelte
packages/server/src/components/GoogleLoginButton.svelte
packages/server/src/components/Nav.svelte
packages/server/src/components/SlackLoginButton.svelte
packages/server/src/routes/provider/alert/create.svelte
packages/server/src/routes/provider/bot.svelte
packages/server/src/routes/provider/index.svelte
packages/server/src/server.js
packages/server/src/template.html
packages/server/src/utility/slackbot.ts

- move all static resources for portal under `/static` directory
- make sapper app explicitly ignore paths that don't belong to the portal
- serve react root for non-sapper routes when no other middleware applies (fixes deep linking to web client)
This is the last big cleanup piece for the routing. The user should see a 404 page from the portal when appropriate; same for the web client. This, along with #375, also seems to solve the OAuth issues (knock on wood).

🐛 Fix routing conficts between portal and web

---

packages/server/src/routes/api/bot/destroy-all-sessions.ts
packages/server/src/worker.ts
packages/server/src/worker/mq.ts
packages/server/src/worker/processJobDestroyAllSessions.ts
packages/server/src/worker/workerTypes.ts

**Should land after #381**
When making OAuth configuration changes or if the session secret somehow got disclosed, it would be necessary to destroy all user sessions.
This PR adds a worker job to drop the session collection (Mongoose will recreate it) + an endpoint to handle the command from `upswyngbot`.

🤖 Create upswngbot command and worker job to delete all user sessions

---

packages/server/src/components/ResourceScheduleDisplay.svelte
packages/server/src/routes/provider/resource/draft/[_id].svelte

This PR closes #167.
Adds a label to draft resources that informs who created the draft.
_example of draft created by user with both username and email_
_example of draft created by user with only email (we're not guaranteed to have a name)_

add created by label to drafts

---

packages/server/src/routes/provider/resource/draft/[_id].svelte

Fixes the route of the redirect that occurs after deleting a draft.

fix: redirect route after draft deletion

---

packages/server/src/routes/provider/alert/create.svelte

This PR closes #414 
1. Adds an interface to query the FontAwesome GraphQL API for useable icons and select one for an alert.
2. Adds the wind Icon as a default option

:sparkles: add ability to search for icons when creating an alert

---

packages/server/src/models/Category.ts

Updates the category endpoint to not return trashed resources.

fix: update the category endpoint to only return non-trashed resources

---

packages/web/src/App.tsx
packages/web/src/components/HomeButtons.tsx

This fixes an issue with the "Job Training" category routing that was displaying our 404 page on sub-categories.

fix: job training routing

---

packages/server/src/routes/provider/resource/[resourceId].svelte

This PR closes #339
Fixes a minor visual bug that caused the badge to appear on top of menu items.
🙂

Set bulma-badge z-index lower to prevent overlap with menu items

---

packages/server/src/routes/provider/resource/draft/[_id].svelte

This PR closes #422 
Renders a simple view of the draft resource for non-admin users, while hiding the admin-specific approve/delete draft buttons.
Feature/improvement ideas:
1. I think this screen should have an info banner at the top along the lines of: "Your draft resource has been submitted and is currently awaiting review by one of our administrators". I think that would be good on the screen where you create the draft as well. The process (create draft -> await approval by admin -> resource created) wasn't clear to me from the provider portal until I started looking at the code.
2. Render a `ResourceEditor` (same component used to create the draft) on this screen, so that a user can make corrections to their draft. Bit complicated because we get into needing to lock the draft while …

Non-admin draft resource view

---

packages/web/src/components/__tests__/BackButton.test.tsx
packages/web/src/components/__tests__/HomeButtons.test.tsx
packages/web/src/components/__tests__/Hotlines.test.tsx
packages/web/src/components/__tests__/Resource.test.tsx

This PR does not close an issue
Adds i18next mocks/subs as applicable via https://react.i18next.com/misc/testing
This PR (or just the changes from this PR) are needed in order for #469 to pass CI (and future localization PRs)

add i18next mocks to tests

---

packages/web/src/components/Schedule.tsx

Moves comment headers to the top of schedules rather than appearing below.

fix: move comment headers to top of comment groups

---

packages/server/.env.example
packages/server/src/app.ts
packages/server/src/server.js

This PR closes #474
https://github.com/CodeForBoulder/upswyng/issues/474
Removes remaining references to beta

removes remaining references to beta

---

packages/common/src/i18n/en.ts
packages/common/src/i18n/es.ts
packages/web/src/components/Resource.tsx

Adds a warning above the hours on each resource, instructing users to check website for more details.
This is important because the situation surrounding COVID-19 is changing weekly. We aren't in a state where we can guarantee up-to-date information so it's best to warn them to contact the provider for more details.

feat: add hours warning to resource page

---

packages/web/src/components/HomeButton.tsx

This PR closes #487
Fixes the issue where the HomeButton background would not match the height of its row if its neighbor had a greater height.

fix issue 487: HomeButton heights

---

README.md
packages/server/src/routes/provider/alert/create.svelte
packages/server/src/template.html

This PR closes #[417]
This changes the FontAwesome kit to 5.14.0 in the server to match the web project.

Standardize FontAwesome

---

packages/web/src/components/BackButton.tsx
packages/web/src/components/PageBanner.tsx

please add banner style updates V2
