CodeForBoulder/upswyng

README.md
Remove extra information from readme generated from Create React App.
=> Update readme with application description

README.md
This PR adds a netlify status badge to the readme.
=> Netlify status badge

.gitignore, .travis.yml, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, package-lock.json, package.json, src/App.js, src/index.css
This PR closes #19. It adds prettier with a pre-commit hook.  It also includes VS Code configuration for in editor debugging with Chrome, in editor Jest testing and Prettier formatting on file save.
=> Add prettier with commit hook and vscode helpers

.github/pull_request_template.md
This PR closes #18 
Adds a PR template for requestors to follow
=> Create initial pull request template

src/components/Carousel.jsx, src/components/Carousel.test.js, src/components/Resource.jsx, src/components/Resource.test.js
This PR does not directly address an issue.
Adds a `<Carousel/>` component that will eventually be used for the image slider found on #29.
=> Add/listing page/carousel

.travis.yml
This PR fixes a build issue in Travis.
=> Pin build node version to v11

package-lock.json, src/components/Home.tsx
This PR adds a Netlify badge to the home page in accordance with their [Open Source Policy](https://www.netlify.com/legal/open-source-policy/).
=> Add Netlify logo to homepage

package-lock.json, package.json, src/App.styles.ts, src/components/Details.tsx, src/components/Resource.test.tsx, src/components/Resource.tsx, src/components/Schedule.tsx, src/types.ts, src/utils/schedule.ts
Adds rendering and styles of the top information on the resource page including:
- service name
- phone
- hours
=> update listing page top info

src/components/CheckboxInput.tsx, src/components/Map.tsx, src/components/Resource.test.tsx, src/components/Resource.tsx
- adds a Google map showing the location of the given resource
- creates a new `<CheckboxInput/>` to act as a styled interface to material-ui's `<FormControlLabel/>` and `<Checkbox/>` input
- updates the "toggle directions" button to be a checkbox
- There was some slapping together done in the `<Map/>` component and I plan on refactoring it a bit to clean it up. That will also include some TS updates and come in a separate PR.
- add listed directions beneath the map
=> Add Google Map to Resource

src/components/useSimilarSearchResults.tsx
=> Add useSimilarSearchResults

src/components/Schedule.tsx
Updates the schedule output on a resource page to group times by day.
=> update <Schedule/> to group times by day

data_pipeline/algolia-update.js
Updates the script used to populate Algolia to also include a charity's description.
=> add description to algolia-update

src/App.tsx
- adds the individual resource page back as a route
=> add the Resource page back as a route

data_pipeline/algolia-update.js
Updates the script used to publish to Algolia to also include a resource's service field.
=> add service to algolia index

src/components/Schedule.tsx, src/utils/schedule.ts
Adds handling of a resource schedule not existing, as seen with "Boulder County AIDS Project (BCAP) - Longmont".
=> handle empty schedule

src/components/CategoryBanner.tsx, src/components/Food.tsx, src/components/Health.tsx, src/components/Hygiene.tsx, src/components/JobTraining.tsx, src/components/Resources.tsx, src/components/Shelters.tsx, src/components/SocialServices.tsx, src/components/Transit.tsx, src/components/WifiTech.tsx
Adds the category banner to the top of each category page.
=> Add category banner

src/components/Categories.tsx, src/components/CategoryResults.tsx, src/components/ResourceCard.tsx, src/components/SearchResults.tsx
This PR closes #121 
- adds placeholder icons to category list page
=> add placeholder icons to categories list

src/components/HomeButtons.tsx, src/components/HomeLink.tsx, src/components/Resource.tsx, src/types.ts
- adds a website link to the resource if it is available
- refactors the rendering of other possibly missing properties
=> add resource's website to resource page

src/components/Categories.tsx
- updates the order of the subcategories based of feedback from our project manager
- relabels "Addiction Recovery Services" to "Addiction"
=> Update order of subcategories

public/index.html, src/components/About.tsx
This PR does not close an issue
- replaces instances of "homeless" to "unhoused"
- updates the index's meta description to match the content on the "About" page
=> update instances of 'homeless' to 'unhoused'

src/App.styles.ts, src/App.tsx, src/DataMocks.ts, src/components/BannerColorContext.tsx, src/components/Categories.tsx, src/components/PageBanner.tsx, src/components/Resource.tsx, src/components/Search.tsx, src/components/__tests__/Resource.test.tsx, src/types.ts
- updates the banner color on a resource page to match the color of the last category page, if available
- if a category page was not the previous page, it uses the color associated with the parent category of the first subcategory on the resource
=> Update Resource Page Banner Color

README.md, public/index.html, src/components/About.tsx, src/components/Logo.tsx, src/components/PrivacyPolicy.tsx
=> changed the upSwyng to UpSwyng

Procfile, package.json, packages/upswyng-server/Procfile, packages/upswyng-server/package.json
Merge broke deployment for the server.
=> 💚 Fix heroku Procfile and server scripts

package.json
=> Update update node engine on root package.json

packages/upswyng-web/src/utils/apiClient.ts
Increases the timeout for a request to the API from 10 seconds to 15 seconds.
=> increase apiClient timeout to 15 seconds

.travis.yml, clean.js, package.json, packages/upswyng-core/package.json, packages/upswyng-server/package.json, packages/upswyng-types/package.json, packages/upswyng-types/tsconfig.build.json, packages/upswyng-web/package.json
Update the individual `build` commands in the packages to ensure that their dependencies get built when they do.
=> 🏗 Tweak build scripts

.vscode/extensions.json, packages/upswyng-web/src/utils/apiClient.ts
=> 🐛 Fix web client apiClient path

packages/upswyng-server/showBuildNotification.js, packages/upswyng-server/src/components/ResourceIssueNotification.svelte, packages/upswyng-server/src/routes/resource/[resourceId].svelte
=> ✨ Create UI button to resolve and unresolve issues

.eslintrc.js, packages/upswyng-server/package.json, packages/upswyng-server/src/components/Nav.svelte, packages/upswyng-server/src/models/ResourceIssue.ts, packages/upswyng-server/src/routes/api/resource/issues/[resourceId].ts, packages/upswyng-server/src/routes/api/resources/issues/index.ts, packages/upswyng-server/src/routes/resource/issues/index.svelte, yarn.lock
- Create a page where admins can view issues
- Add link to "More" dropdown on the nav bar
- Add endpoint to query issues
=> ✨ Create resource issue page

packages/upswyng-server/src/components/ScheduleSelector.svelte
Schedule selector was throwing when trying to add a new schedule entry.
=> 🐛 Fix schedule selector bug

packages/upswyng-server/src/components/ScheduleSelector.svelte
This adds the ability to put a schedule entry in like "The 1st and 3rd Wednesdays of the month from 6:00PM to 8:00PM"
=> ✨ Schedule Selector - specify occurrences of day in month

packages/upswyng-core/package.json, packages/upswyng-core/src/EventLog.ts, packages/upswyng-core/src/ResourceSchedule.ts, packages/upswyng-server/src/models/EventLog.ts, packages/upswyng-server/src/routes/api/resource/draft/delete/[_id].ts, packages/upswyng-server/src/utility/authHelpers.ts, packages/upswyng-types/src/TEventLog.ts, packages/upswyng-types/src/index.ts
Create the utility class, types, and schema to log events. Includes 'draft_deleted' log type as example.
=> ✨ Create event log

.gitignore, package.json, packages/upswyng-server/src/routes/api/resource/issue/[resource_issue_id].ts, packages/upswyng-server/src/routes/resource/issue/[resource_issue_id].svelte, packages/upswyng-server/src/routes/resource/issues/index.svelte
Add link to individual Resource Issue from overall Resource Issues page.
=> ✨ Create Resource Issue endpoint and page

packages/upswyng-server/src/components/EventLogItem.svelte, packages/upswyng-server/src/components/ResourceDiff.svelte, packages/upswyng-server/src/routes/eventlogs.svelte
=> 💄 Enhance UX and beautify UI of Event Log feed

packages/upswyng-server/src/models/Subcategory.ts
Just broke all the APIs and I will now fix them.
=> 🚑 Fix broken API

packages/upswyng-server/.env.example, packages/upswyng-server/package.json, packages/upswyng-server/src/models/Category.ts, packages/upswyng-server/src/models/Subcategory.ts, packages/upswyng-server/src/routes/api/resource/draft/approve/[_id].ts, packages/upswyng-server/src/routes/api/resource/draft/delete/[_id].ts, packages/upswyng-server/src/routes/api/resource/issues/_setResolved.ts, packages/upswyng-server/src/server.js, packages/upswyng-server/src/utility/slackbot.ts, packages/upswyng-web/src/components/useResourcesByCategory.tsx, yarn.lock
Add slack integration via the **upswyngbot**. Currently, the bot relays EventLogs posted from the server. I would also like the bot to be able to run commands, like a monitoring job.
=> ✨ Add slack integration

packages/upswyng-server/.env.example, packages/upswyng-server/package.json, packages/upswyng-server/src/utility/slackbot.ts, yarn.lock
This will show an indication of whether the server (and bot) is online in Slack.
=> ✨ Add RTM API to slackbot

packages/upswyng-server/.env.example, packages/upswyng-server/src/components/ScheduleSelector.svelte
=> 💄 Hide schedule selector every day button on mobile

packages/upswyng-native/src/components/Home.tsx, packages/upswyng-native/src/useSearchResults.tsx, packages/upswyng-server/src/components/ResourceScheduleDisplay.svelte, packages/upswyng-server/src/components/ScheduleSelector.svelte, packages/upswyng-server/src/components/ScheduleSelectorScheduleItem.svelte
=> 💄 Schedule item redesign

packages/upswyng-server/src/components/EventLogItem.svelte, packages/upswyng-server/src/routes/api/resource.ts, packages/upswyng-server/src/utility/slackbot.ts, packages/upswyng-types/src/index.ts
=> ✨ Add Event Log for new drafts

.travis.yml
=> 🏗 Add server data pipeline build to CI

packages/upswyng-server/src/components/ResourceEditor.svelte, packages/upswyng-server/src/components/ScheduleSelector.svelte, packages/upswyng-server/src/components/SubcategoryInput.svelte, packages/upswyng-server/src/routes/resource/[resourceId].svelte
- Fix bug where issue warning banner wasn't showing
- Put a box around non-modifiable parameters
- Fix spacing and heading sizes
- Convert breadcrumbs to bulma breadcrumbs
- Fix submit button running into resource list
=> 💄 Tidy up Resource Editor

README.md
Adds a helpful note about an issue that happened while I was setting up the project for the first time.
=> Mention requiring node version 12.14.x

packages/upswyng-server/src/components/Nav.svelte, packages/upswyng-server/src/models/User.ts, packages/upswyng-server/src/routes/api/users.ts, packages/upswyng-server/src/routes/users.svelte
- Create API endpoint to search for users
- Create page with a table view of users
- Add search/sort features to users (with 100s, we wouldn't want to paginate through them to get to the ones we want -- maybe use [mongoose-fuzzy-searching](https://www.npmjs.com/package/mongoose-fuzzy-searching))
- Add ability to make user admin/superadmin
=> ✨ [server] Add user endpoint and overview page

packages/upswyng-web/src/components/Temperature.tsx
This PR closes #[insert associated issue number here]
Removes the rendering of the ! icon when weather information is not available. Shows no information when none is available. 
First Contribution!!
=> Updt/update temp display #225

packages/upswyng-server/src/app.ts, packages/upswyng-server/src/server.js
Puts the app startup in the callback of the database connection.
=> Reenable database sessions

packages/upswyng-server/src/app.ts
=> Log app options

packages/upswyng-web/src/components/Map.tsx, packages/upswyng-web/src/components/ResourceList.tsx, packages/upswyng-web/src/components/useResource.tsx, packages/upswyng-web/src/components/useSearchResults.tsx, packages/upswyng-web/src/components/useTemperature.tsx
- removes some of the compile warnings that were mostly the result of missing `useEffect` dependencies
_There is one more warning in `<Map/>` that I won't address this PR. That'll be a bit more involved so I'll address it in a diff PR._
=> fix: remove some compile warnings in web

packages/upswyng-server/src/server.js
Just going to add this in the environment vars instead.
=> Remove logic to modify mongo connection string

packages/upswyng-web/src/App.tsx, packages/upswyng-web/src/components/Resource.tsx, packages/upswyng-web/src/components/ResourceCard.tsx, packages/upswyng-web/src/components/__tests__/Resource.test.tsx, packages/upswyng-web/src/constants.ts, yarn.lock
copy of #235 . checking to see if there was a problem with that specific PR and our travis build spec.
=> feat: update the resource ID to use a slug rather than search param

packages/upswyng-server/src/components/Nav.svelte
Before it just showed "admin".
=> 💄 [server] Add super admin badge on nav bar

packages/upswyng-server/src/routes/api/resources/drafts/mine.ts, packages/upswyng-server/src/routes/resource/index.svelte, packages/upswyng-server/src/utility/slackbot.ts, packages/upswyng-server/static/manifest.json, yarn.lock
=> ✨ [server] Add user's drafts to resources page

README.md
Add a troubleshooting section with a subsection about how to fix errors resulting from a stale build of the local packages.
=> 📝 Add a troubleshooting section to README

packages/upswyng-server/src/routes/api/bot/check-links.ts, packages/upswyng-server/src/routes/bot.svelte, packages/upswyng-server/src/worker.ts, packages/upswyng-server/src/worker/mq.ts, packages/upswyng-server/src/worker/processJobCheckLinks.ts, packages/upswyng-server/src/worker/workerTypes.ts
Create a job for `upswyngbot` where the bot checks all the websites in the Resource directory for broken links
- Create types
- Create processor
- Create endopoint
- Update slack with slash command **`/check-links`**
=> ✨ Create Check Links job

README.md
=> 📝 Add some tips for working with yarn workspaces to README

packages/upswyng-web/package.json, packages/upswyng-web/src/App.tsx, packages/upswyng-web/src/components/BackButton.tsx, packages/upswyng-web/src/components/PageBanner.tsx, packages/upswyng-web/src/components/Resource.tsx, packages/upswyng-web/src/components/__tests__/Resource.test.tsx, yarn.lock
This PR closes #168 
1. If a user is on a resource, they are taken back to the previous page. (On the tab that they clicked the resource on).
2. If a user is browsing tabs, they are taken to the index page regardless of how many tabs they clicked on.
=> updt: adds desired back button behavior

packages/upswyng-server/src/utility/userMiddleware.ts
=> 🐛 [server] Skip getting user if there is no grant response

README.md
This PR does close an issue
- simplifies branch naming in contributing section of readme
- adds link to CfB Code of Conduct in contributing section of readme
=> doc: update contributing info in README

packages/upswyng-server/src/components/Nav.svelte
=> ✨ [server] Add admin link to nav bar

.eslintignore, packages/upswyng-server/src/models/Alert.ts, packages/upswyng-server/src/worker.ts, packages/upswyng-server/src/worker/README.md, packages/upswyng-server/src/worker/mq.ts, packages/upswyng-server/src/worker/processJobCheckNewAlerts.ts, packages/upswyng-server/src/worker/workerTypes.ts, packages/upswyng-types/src/TAlert.ts
Add a worker job which checks for alerts which have recently become active. Right now it just logs a message, but eventually it should push a notification.
=> ✨ [server] Create new alert job

packages/upswyng-web/package.json, packages/upswyng-web/public/index.html, packages/upswyng-web/src/App.tsx, packages/upswyng-web/src/components/AlertPanel.tsx, packages/upswyng-web/src/components/AlertsDrawer.tsx, packages/upswyng-web/src/components/GlobalAlertBar.tsx, packages/upswyng-web/src/components/MuiMarkdown.tsx, packages/upswyng-web/src/components/useAlerts.tsx, packages/upswyng-web/src/webTypes.ts, yarn.lock
This PR closes #294
- adds an alert bar to the top of public-facing app
- adds corresponding drawer to display more details on the current alert(s)
- creates `<MuiMarkdown/>` component that wraps markdown, converted by [react-markdown](https://github.com/rexxars/react-markdown), in MUI components
- adds font awesome to the project to display alert icons chosen by user in admin interface
_alert bar with one alert_
_alert bar with multiple alerts_
_alert drawer with multiple alerts_
_alert without alert details on hover/touch_
_alert using markdown_
=> display alert bar

packages/upswyng-server/src/routes/resource/[resourceId].svelte
This PR does close an issue.
This fixes a problem with viewing a provider in the provider portal when not logged in.
=> fix: issue with viewing resources when unauthenticated

packages/upswyng-server/src/components/Autocomplete.svelte, packages/upswyng-server/src/components/AutocompleteInput.svelte, packages/upswyng-server/src/components/AutocompleteItem.svelte, packages/upswyng-server/src/components/ResourceSearch.svelte, packages/upswyng-server/src/components/ResourceSearchResult.svelte, packages/upswyng-server/src/routes/index.svelte, packages/upswyng-server/src/routes/resource/index.svelte, packages/upswyng-server/src/routes/subcategory/[stub].svelte
- implements new styles for the provider search
- creates new `<Autocomplete/>` which implements ARIA Autocomplete accessibility attributes based on [ARIA best practices](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html)
- wraps provider search in new `<Autocomplete/>` component
- moves the search component towards the top of the main search providers page
- updates various use of "Resource" to "Provider"
_hover via mouse styles_
_focus via keyboard styles_
=> feat: update provider search styles

packages/upswyng-server/src/routes/api/resources/drafts/mine.ts, packages/upswyng-server/src/routes/api/resources/issues/index.ts
=> ♻️ Simplify some server endpoint returns

packages/server/src/components/ResourceEditor.svelte, packages/server/src/components/ScheduleSelector.svelte
- updates the layout of the schedule in the resource editor
- updates use of "Resource" to "Provider" in various parts of the application
- moves the "Trash Resource" option to the bottom of the editor page
=> update resource editor

package.json, yarn.lock
Update the heroku postbuild script to build both common and types.
=> ci: heroku postbuild common and types

packages/server/src/app.ts
=> [server] 🐛 Don't show placeholder page for api routes

packages/server/cypress/integration/spec.ts, packages/server/package.json, packages/server/src/components/EventLogs.svelte, packages/server/src/components/ResourceDisplay.svelte, packages/server/src/components/ResourceEditor.svelte, packages/server/src/components/ResourceIssueNotification.svelte, packages/server/src/components/ResourceSearch.svelte, packages/server/src/routes/api/resource/[resourceId].ts, packages/server/src/routes/api/resource/draft/delete/[_id].ts, packages/server/src/routes/api/resource/issues/[resourceId].ts, packages/server/src/routes/api/resource/issues/_setResolved.ts, packages/server/src/routes/api/resources/issues/user-report.ts, packages/server/src/routes/provider/index.svelte, packages/server/src/routes/provider/resource/[resourceId].svelte, packages/server/src/routes/provider/resource/create.svelte, packages/server/src/routes/provider/resource/draft/[_id].svelte, packages/server/src/routes/provider/resource/index.svelte, packages/server/src/routes/provider/resource/issue/[resource_issue_id].svelte, packages/server/src/routes/provider/resource/issues/index.svelte, packages/server/src/routes/provider/subcategory/[stub].svelte, packages/server/src/routes/provider/users.svelte, packages/server/src/utility/handleCommandFromSlack.ts, packages/server/static/manifest.json
Changes all _visual_ use of "resource" and "provider" to "service provider" in the service provider portal.
=> update 'Provider Portal' to 'Service Provider Portal'

CONTRIBUTING.md, README.md
=> :truck: Move contribution guidelines to separate file

packages/server/src/app.ts
=> 🚑 Fix placeholder check

packages/server/src/models/Subcategory.ts
**Submit after #381**
Closes Issue #383.
- Optionally filter out deleted resources from subcategory list
=> 🐛 [server] Filter deleted resources from subcategory list

packages/server/package.json, packages/server/src/app.ts, yarn.lock
Add request logger middleware when running dev server.
=> 🔊 [server] Add morgan logger middleware

packages/server/src/worker/README.md
=> 📄 Add link to destroy-all-sessions PR to worker readme

packages/web/src/components/Categories.tsx
Adds a safe parking subcategory under shelter option
=> Add safe parking subcategory under shelter option.

CONTRIBUTING.md, README.md, packages/server/README.md, packages/web/README.md
Adds some more instructions to assist devs with running the application and contributing.
=> docs: improve contributing and setup documentation

packages/native/.env.example, packages/server/.env.example, packages/server/README.md, packages/server/src/bin/syncStrappd.ts, packages/server/src/bin/updateAlgolia.ts, packages/server/src/server.js, packages/server/src/worker.ts
We're migrating our DB to a different host, and that comes with some slight changes in how we connect:
- the database name is now part of the connection URL
- the prod DB detection test needs to be updated
=> chore: update db connection config

packages/server/src/components/ResourceEditor.svelte
This PR closes #421 
Adds some helpful text to the provider forms.
🙂
=> Add street view, lat and long label help text

packages/common/src/i18n/en.json, packages/common/src/i18n/es.json, packages/web/src/i18n.ts
This PR closes #443 
Moves translations to JSON files in the common package.
Would love to look into updating the translations and getting this live/selectable on the frontend as a next step!
🙂
=> Move translations to separate json files

packages/native/package.json, packages/server/package.json, packages/server/src/routes/api/bot/sync-algolia.ts, packages/server/src/routes/api/resource/draft/approve/[_id].ts, packages/server/src/utility/algoliaIndex.ts, packages/web/package.json, yarn.lock
This PR closes #433 
This PR makes it so that our Algolia index is synced with new/edited resources when a draft is approved.
This Pr also adds the endpoint that upswyngbot can use to kick off a full sync job. (I'll add the command to upswyngbot once David can get me access)
This PR also bumps Axios because of its new security vulnerability.
=> :zap: update algolia sync

packages/web/src/components/HomeButtons.tsx, packages/web/src/components/HomeLink.tsx, packages/web/src/components/MonthlySchedule.tsx, packages/web/src/components/__tests__/HomeButtons.test.tsx, packages/web/src/webTypes.ts
This PR closes #473 
- fixes #473 
- removes some warnings in the dev console shown on the home page
=> fix: monthly date offsets

packages/common/src/i18n/en.ts, packages/common/src/i18n/es.ts, packages/web/src/components/MenuDrawer.tsx, yarn.lock
This PR closes #449 
Localizes the main menu
=> localize main menu

README.md, packages/common/src/i18n/en.ts, packages/common/src/i18n/es.ts, packages/web/src/components/Hotlines.tsx
…onment configuration. remediate [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6380, MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017
This PR closes issue #475
This PR is meant to help others troubleshoot their environment setup using Ubuntu/WSL2
=> add Safehouse Progressive Alliance for Nonviolence hotline (#475) || README ubdated to include troubleshooting steps for WSL2/Ubuntu environment

packages/web/src/components/Header.tsx, packages/web/src/components/Temperature.tsx, packages/web/src/components/TranslationSelect.tsx
Addresses a problem with the header wrapping on smaller screensizes.
=> fix: address header wrapping issues

packages/common/src/i18n/en.ts, packages/common/src/i18n/es.ts, packages/web/src/components/CoordinatedEntry.tsx
Replaces the "6 month residency requirement" on the "Coordinated Entry" page with a warning about not being guaranteed to qualify for services.
=> replace 6 month notice in coordinated entry
